webserver:
  image: webdevops/php-nginx:7.2
  volumes:
    - ./:/var/www
  environment:
    - WEB_SERVER_NAME=finizens.local
    - WEB_DOCUMENT_ROOT=/var/www/public
    - WEB_DOCUMENT_INDEX=index.php
  ports:
    - 80:80